---
# Handlers for dokku notifications

- name: restart docker
  sudo: true
  service: name=docker state=restarted

- name: install plugins
  sudo: true
  command: dokku plugins-install

- name: restart nginx
  sudo: true
  service: name=nginx state=restarted
