---
# Setup dokku-alt on a node
- name: Docker APT key
  sudo: true
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
  tags:
    - docker

- name: Docker repo
  sudo: true
  apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
  tags:
    - docker

- name: Dokku APT key
  sudo: true
  apt_key: url=https://packagecloud.io/gpg.key
  tags:
    - dokku

- name: Dokku repo
  sudo: true
  apt_repository: repo='deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main' state=present
  tags:
    - dokku

- name: Dokku options
  sudo: true
  debconf: name=dokku question='dokku/vhost_enable' value='true' vtype='boolean'
  tags:
    - dokku

- name: Dokku hostname
  sudo: true
  debconf: name=dokku question='dokku/hostname' value='{{ dokku_host }}' vtype='string'
  tags:
    - dokku

- name: Install Herokuish
  sudo: true
  apt: name=herokuish=0.0.1 update_cache=yes
  tags:
    - dokku

- name: Install Dokku
  sudo: true
  apt: name=dokku=0.3.26 update_cache=yes
  tags:
    - dokku

- name: Configure Docker
  sudo: true
  copy: src=docker.default dest=/etc/default/docker owner=root mode=0644
  notify: restart docker
  tags:
    - docker

- name: Start Docker
  sudo: true
  service: name=ssh state=started enabled=true
  tags:
    - docker

- name: Allow HTTP
  sudo: true
  ufw: rule=allow port=80 proto=tcp
  tags:
    - security
    - firewall

- name: Allow HTTPS
  sudo: true
  ufw: rule=allow port=443 proto=tcp
  tags:
    - security
    - firewall

- name: Postgres plugin install
  sudo: true
  git: repo=https://github.com/jeffutter/dokku-postgresql-plugin.git dest=/var/lib/dokku/plugins/postgresql
  notify: install plugins
  tags:
    - dokku
    - plugin

- name: Nginx Default
  sudo: true
  copy: src=nginx.default dest=/etc/nginx/conf.d/default.conf owner=root mode=0644
  notify: restart nginx
  tags:
    - dokku
