---
# Setup dokku on a node
- name: Docker APT key
  sudo: true
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  tags:
    - docker

- name: Docker repo
  sudo: true
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
  tags:
    - docker

- name: Install Docker
  sudo: true
  apt: name=docker-engine update_cache=yes
  tags:
    - docker

- name: Configure Docker
  sudo: true
  copy: src=docker.default dest=/etc/default/docker owner=root mode=0644
  notify: restart docker
  tags:
    - docker

- name: Start Docker
  sudo: true
  service: name=ssh state=started enabled=true
  tags:
    - docker

- name: Dokku APT key
  sudo: true
  apt_key: keyserver=keys.gnupg.net id=EAD883AF
  tags:
    - dokku

- name: Dokku repo
  sudo: true
  apt_repository: repo='deb https://dokku-alt.github.io/dokku-alt /' state=present
  tags:
    - dokku

- name: Install Dokku
  sudo: true
  apt: name=dokku-alt update_cache=yes
  tags:
    - dokku

- name: Dokku hostname
  sudo: true
  copy: content={{ dokku_host }} dest=/home/dokku/HOSTNAME owner=root mode=0644
  tags:
    - dokku

- name: Dokku vhost
  sudo: true
  copy: content={{ dokku_vhost }} dest=/home/dokku/VHOST owner=root mode=0644
  tags:
    - dokku

- name: Allow HTTP
  sudo: true
  ufw: rule=allow port=80 proto=tcp
  tags:
    - security
    - firewall

- name: Allow HTTPS
  sudo: true
  ufw: rule=allow port=443 proto=tcp
  tags:
    - security
    - firewall
