---
# This playbook contains common plays that will be run on all nodes.
- name: Update APT cache
  sudo: True
  apt: update_cache=yes cache_valid_time=3600

- name: Install base packages
  sudo: True
  apt: name={{ item }}
  with_items:
   - python-software-properties
   - dpkg-dev
   - build-essential
   - sudo
   - ntp
   - vim
   - wget

- name: Start the ntp service
  sudo: True
  service: name=ntp state=started enabled=true

- name: Install ssh packages
  sudo: True
  apt: name={{ item }}
  with_items:
   - openssh-client
   - openssh-server

- name: Configure ssh file
  sudo: True
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root mode=0644
  notify: restart ssh

- name: Start the ssh service
  sudo: True
  service: name=ssh state=started enabled=true

- name: Install fail2ban packages
  sudo: True
  apt: name=fail2ban

- name: Configure fail2ban file
  sudo: True
  copy: src=jail.local dest=/etc/fail2ban/jail.local owner=root mode=0644
  copy: src=common.local dest=/etc/fail2ban/filter.d/common.local owner=root mode=0644
  notify: restart fail2ban

- name: Start the fail2ban service
  sudo: True
  service: name=fail2ban state=started enabled=true

- name: Install ufw packages
  sudo: True
  apt: name=ufw

- name: Start the ufw service
  sudo: True
  service: name=ufw state=started enabled=true

- name: Enable UFW
  sudo: True
  ufw: state=enabled policy=deny

- name: Allow OpenSSH
  sudo: True
  ufw: rule=allow name=OpenSSH
