# This playbook contains common plays that will be run on all nodes.
- name: Update APT cache
  sudo: True
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - packages

- name: Install base packages
  sudo: True
  apt: name={{ item }}
  with_items:
    - python-software-properties
    - unattended-upgrades
    - dpkg-dev
    - debconf
    - debconf-utils
    - build-essential
    - sudo
    - ntp
    - vim
    - wget
    - apt-transport-https
  tags:
    - packages

- name: Start the ntp service
  sudo: True
  service: name=ntp state=started enabled=true

- name: Install ssh packages
  sudo: True
  apt: name={{ item }}
  with_items:
    - openssh-client
    - openssh-server
  tags:
    - security
    - ssh

- name: Configure ssh file
  sudo: True
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root mode=0644
  notify: restart ssh

- name: Start the ssh service
  sudo: True
  service: name=ssh state=started enabled=true
  tags:
    - security
    - ssh

- name: Install fail2ban packages
  sudo: True
  apt: name=fail2ban
  tags:
    - security
    - fail2ban

- name: Configure fail2ban file
  sudo: True
  copy: src=jail.local dest=/etc/fail2ban/jail.local owner=root mode=0644
  copy: src=common.local dest=/etc/fail2ban/filter.d/common.local owner=root mode=0644
  notify: restart fail2ban
  tags:
    - security
    - fail2ban

- name: Start the fail2ban service
  sudo: True
  service: name=fail2ban state=started enabled=true
  tags:
    - security
    - fail2ban

- name: Install ufw packages
  sudo: True
  apt: name=ufw
  tags:
    - security
    - firewall

- name: Start the ufw service
  sudo: True
  service: name=ufw state=started enabled=true
  tags:
    - security
    - firewall

- name: Enable UFW
  sudo: True
  ufw: state=enabled policy=deny
  tags:
    - security
    - firewall

- name: Allow OpenSSH
  sudo: True
  ufw: rule=allow name=OpenSSH
  tags:
    - security
    - firewall

- name: Install mail server packages
  sudo: True
  apt: name=postfix
  tags:
    - mail

- name: Start the postfix service
  sudo: True
  service: name=postfix state=started enabled=true
  tags:
    - mail

- name: Configure auto-upgrades
  sudo: True
  copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades owner=root mode=0644
  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root mode=0644
  tags:
    - packages
